USE [master]
GO

/****** Object:  Database [ProjectShoes]    Script Date: 6/22/2022 1:44:12 PM ******/
DROP DATABASE [ProjectShoes]
GO

/****** Object:  Database [ProjectShoes]    Script Date: 6/22/2022 1:44:12 PM ******/
CREATE DATABASE [ProjectShoes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectShoes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\ProjectShoes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjectShoes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\ProjectShoes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectShoes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectShoes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectShoes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectShoes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectShoes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectShoes] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectShoes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectShoes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectShoes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectShoes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectShoes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectShoes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectShoes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectShoes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectShoes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectShoes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectShoes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectShoes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectShoes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectShoes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectShoes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectShoes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectShoes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectShoes] SET RECOVERY FULL 
GO

ALTER DATABASE [ProjectShoes] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectShoes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectShoes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectShoes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectShoes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProjectShoes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjectShoes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ProjectShoes] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProjectShoes] SET  READ_WRITE 
GO

